/* 
   TITLE           Terms						Chapter2Exercise5.cpp
   Bjarne Stroustrup "Programming: Principles and Practice Using C++"
   COMMENT
		Objective: Define the terms from the chapter.
			Input: -
		   Output: -
           Author: Chris B. Kirov
			 Date: 10.04.2014		   
*/
#include "../../std_lib_facilities.h"

/*
Term:									Definition:

//										double "slash" token: indicates a start of a comment.

<<										syntax: destination << source; insertion operator:
                                        inserts source variable into destination stream.

comment									descriptive part of a code.

compiler								software for  that processes statements written in 
										a particular programming language and turns 
									    them into machine language or "code" that a computer's processor uses.

compile-time error						error during compilaion (linking, syntax, etc.)

cout									standard output stream: it prints its value to the screen.

executable								a .exe file: a successfully compiled and linked source code.

function								syntax: returning type identifie (parameter list) { body };
										a type of procedure or routine of block of organized, 
										reusable code that is used to perform a single, related action.

header									a file with extension .h which contains code to be shared between several source files. 
										It could be written by a programmer or coming from a compiler.

IDE										integrated development environment (IDE); 
										a software application that provides facilities for software development
										consisted of a source code editor, build automation tools and a debugger.

#include								syntax: #include "file.h" (<file.h>); 
										preprocessor directive making  the compiler to replace that line with the
										entire text of the contents of the named source file.

library									a collection of precompiled routines that a program can use,
                                        stored in object format (don't need to be explicitly linked to every program).

linker									a computer program that takes objects generated by a compiler and links them
										to standard library function, hence making them executable program.

main()									an entry point is where control is transferred from the operating system to
										a computer program, at which place the processor enters a program or
										a code fragment and execution begins.

object code								a sequence of statements or instructions in a computer language procuded
										by the compiler.

output									the signals or data sent from a source (function, program, system).

program									a specific set of ordered operations (a one-at-a-time sequence of instructions) for a computer to perform.

source code								collection of computer instructions written using some human-readable computer language, usually as text.

statement								is the smallest standalone element that epxresses an action.

*/